<?php


require(__DIR__ . DIRECTORY_SEPARATOR . 'WebserviceClient.php');
$host = 'https://host/webservice/v1';
$token = 'token';
$selfSigned = true; 
$api = new IXCsoft\WebserviceClient($host, $token, $selfSigned);
$dados = array(
    'razao' => 'Teste API',
    'fantasia' => '',
    'id_candato_tipo' => '',
    'id_campanha' => '',
    'id_concorrente' => '',
    'id_perfil' => '',
    'responsavel' => '',
    'indicado_por' => '',
    'status_prospeccao' => 'C',
    'tipo_pessoa' => 'F',
    'cnpj_cpf' => '',
    'ie_identidade' => '',
    'data_nascimento' => '',
    'filial_id' => '',
    'ativo' => 'S',
    'data_cadastro' => '',
    'prospeccao_ultimo_contato' => '',
    'prospeccao_proximo_contato' => '',
    'id_vendedor' => '',
    'id_conta' => '',
    'id_vd_contrato_desejado' => '',
    'cadastrado_via_viabilidade' => 'N',
    'ultima_atualizacao' => 'CURRENT_TIMESTAMP',
    'id_contato_principal' => '',
    'fone' => '',
    'telefone_comercial' => '',
    'telefone_celular' => '',
    'whatsapp' => '',
    'ramal' => '',
    'email' => 'teste@teste.com',
    'contato' => '',
    'website' => '',
    'skype' => '',
    'facebook' => '',
    'id_condominio' => '',
    'bloco' => '',
    'apartamento' => '',
    'cep' => '',
    'endereco' => '',
    'numero' => '',
    'bairro' => '',
    'cidade' => '444',
    'complemento' => '',
    'referencia' => '',
    'uf' => '1',
    'moradia' => 'P',
    'tipo_localidade' => 'U',
    'latitude' => '',
    'longitude' => '',
    'external_id' => '',
    'external_system' => '',
    'crm' => 'S',
    'pipe_id_organizacao' => '',
    'idx' => '',
    'crm_data_novo' => '',
    'crm_data_sondagem' => '',
    'crm_data_apresentando' => '',
    'crm_data_negociando' => '',
    'crm_data_vencemos' => '',
    'crm_data_perdemos' => '',
    'crm_data_abortamos' => '',
    'crm_data_sem_viabilidade' => '',
    'crm_data_sem_porta_disponivel' => '',
    'obs' => '',
    'alerta' => '',
    'status_viabilidade' => '',
    'tipo_rede' => '',
    'rede_ativacao' => 'P',
    'operador_neutro' => '',
    'resultado_calc_vel' => '',
    'qtd_pessoas_calc_vel' => '',
    'qtd_smart_calc_vel' => '',
    'freq_smart_calc_vel' => '',
    'qtd_celular_calc_vel' => '',
    'freq_celular_calc_vel' => '',
    'qtd_computador_calc_vel' => 'NULL',
    'freq_computador_calc_vel' => '',
    'qtd_console_calc_vel' => 'NULL',
    'freq_console_calc_vel' => 'NULL',
    'plano_negociacao_auto_viab' => '',
    'tipo_cobranca_auto_viab' => '',
    'data_reserva_auto_viab' => '',
    'melhor_periodo_reserva_auto_viab' => ''
);
$api->post('crm_canditados', $dados);
$retorno = $api->getRespostaConteudo(false);
echo '<pre>';
print_r($retorno);

?>