<?php


require(__DIR__ . DIRECTORY_SEPARATOR . 'WebserviceClient.php');
$host = 'https://host/webservice/v1';
$token = 'token';
$selfSigned = true;
$api = new IXCsoft\WebserviceClient($host, $token, $selfSigned);
$dados = array(
    'id_cliente' => '1',
    'id_conta' => '1',
    'id_conta_class_finan_a' => '',
    'filial_id' => '1',
    'documento' => '',
    'data_emissao' => '27/09/2023',
    'data_vencimento' => '29/09/2023',
    'valor' => '5000.0',
    'previsao' => 'N',
    'tipo_recebimento' => 'Boleto',
    'id_carteira_cobranca' => '1',
    'obs' => '',
    'data_inicial' => '',
    'data_final' => '',
    'status' => 'A',
    'id_saida' => '',
    'liberado' => 'S',
    'nn_boleto' => '',
    'gateway_link' => '',
    'gerencianet_token' => '',
    'tipo_conta' => '',
    'id_cobranca' => '',
    'status_cobranca' => '',
    'id_nota_gerada' => '0',
    'id_im_imovel' => '',
    'impresso' => 'N',
    'arquivo_remessa_baixado' => '',
    'duplicata' => '',
    'id_sip' => '',
    'tipo_renegociacao' => '',
    'id_renegociacao' => '',
    'id_renegociacao_novo' => '',
    'boleto' => '',
    'forma_recebimento' => 'M',
    'credito_data' => '',
    'baixa_data' => '',
    'baixa_id_operador' => '',
    'cancelamento_id_operador' => '',
    'numero_parcela_recorrente' => '',
    'nparcela' => '',
    'id_contrato_principal' => '',
    'previsao_conta_receita' => 'N',
    'tipo_cobranca' => '',
    'parcela_proporcional' => '',
    'tipo_pagamento_cartao' => '',
    'titulo_protestado' => 'N',
    'desconto_condicional_valor' => 'NULL',
    'validade_desconto_condicional' => 'NULL',
    'id_nota_gerada_opc2' => '',
    'id_nota_gerada_opc3' => '',
    'id_nota_gerada_opc4' => '',
    'valor_aberto' => '',
    'valor_recebido' => '',
    'pagamento_valor' => '',
    'pagamento_data' => '',
    'valor_cancelado' => '',
    'data_cancelamento' => '',
    'origem_importacao' => '',
    'titulo_importado' => 'N',
    'aguardando_confirmacao_pagamento' => 'N',
    'parcelado_cartao' => 'N',
    'recebido_via_pix' => 'N',
    'id_remessa' => '',
    'nn_boleto' => '',
    'boleto' => '',
    'gateway_link' => '',
    'linha_digitavel' => '',
    'id_remessa_alteracao' => '',
    'motivo_alteracao' => '',
    'pix_txid' => '',
    'libera_periodo' => 'N',
    'id_mot_cancelamento' => '',
    'id_contrato' => '',
    'id_contrato_avulso' => '',
    'ultima_atualizacao' => '',
    'botoes_classe_finan' => '',
    'id_conta_class_finan' => '',
    'valor_class_finan' => '',
    'grid_classe_finan' => '',
    'json_class_finan' => '',
    'id_nf_gerada' => '',
    'id_nf_opcional2' => '',
    'id_nf_opcional3' => '',
    'id_nf_opcional4' => ''
);
$api->post('fn_areceber', $dados);
$retorno = $api->getRespostaConteudo(false);
echo '<pre>';
print_r($retorno);

?>

